fix links
Special characters inside backticks lose their meaning. So
`[something](URL)` will not rendered verbatim instead of as a link
when converting to HTML, at least with some renderers such as the one
used by Jekyll, kramdown.

Unfortunately xml2rfc doesn't allow backticks inside the text portion
such as [`something`](URL) either. It aborts with the following error:

> xml2rfc --v3 draft-ietf-cellar-codec-04.xml -o draft-ietf-cellar-codec-04.txt
> Error: XInclude processing failed: Document is empty, line 1, column 1
> Unable to complete processing draft-ietf-cellar-codec-04.xml
> draft-ietf-cellar-codec-04.xml(273): Error: Did not expect element tt there, at /rfc/middle/section[6]/section[3]/section[9]/t[4]/eref[2]/tt
> draft-ietf-cellar-codec-04.xml(273): Error: Did not expect element tt there, at /rfc/middle/section[6]/section[3]/section[9]/t[4]/eref[3]/tt
> draft-ietf-cellar-codec-04.xml(3): Error: Invalid document before running preptool.
> Unable to complete processing draft-ietf-cellar-codec-04.xml

Therefore remove the backticks.